import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Glorious Priesthood Assembly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en_us">
      <body className={` antialiased`}>{children}</body>
    </html>
  );
}
