import type { Metadata } from "next";
import "./globals.css";
import { MemberContextProvider } from "./store/MemberContext";
import { Toaster } from "sonner";
export const metadata: Metadata = {
  title: "Glorious Priesthood Assembly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en_us">
      <body className={` antialiased`}>
        <Toaster />
        <MemberContextProvider>{children}</MemberContextProvider>
      </body>
    </html>
  );
}
